### ISSUE TITLE
`rexray` (encrypted volume plugin)

### ISSUE THREAD

**Issue by jzombie** [jzombie/docker-mqtt-mosquitto-cloudflare-tunnel#21]
Creating an encrypted volume for your data using Docker's volume plugins can enhance the security of your data at rest. Here’s how you can do it using the `rexray` plugin with Docker:

### 1. Install the `rexray` Plugin
First, install the `rexray` Docker volume plugin, which supports volume encryption.

```sh
docker plugin install rexray/s3fs REXRAY_PREEMPT=true
```

### 2. Create an Encrypted Volume
Next, create a Docker volume with encryption enabled. You can configure the `rexray` plugin to use encryption by specifying the necessary options.

```sh
docker volume create \
  --driver rexray/s3fs \
  --opt s3fs-encrypt=true \
  --opt s3fs-opts=allow_other,nonempty \
  --name my-encrypted-volume
```

### 3. Use the Encrypted Volume in a Container
Mount the encrypted volume in your Docker container.

#### Dockerfile
Create a Dockerfile for your application.

```dockerfile
FROM ubuntu:latest
RUN apt-get update && apt-get install -y gocryptfs
RUN useradd -ms /bin/bash secureuser
USER secureuser

# Application setup and entry point
ENTRYPOINT ["your_application"]
```

#### docker-compose.yml
Create a `docker-compose.yml` file to use the encrypted volume.

```yaml
version: '3.7'
services:
  secure-app:
    build: .
    volumes:
      - my-encrypted-volume:/path/to/data
    environment:
      - GCRYPTFS_PASSWORD=your_password
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    user: secureuser
    read_only: true

volumes:
  my-encrypted-volume:
    driver: rexray/s3fs
    driver_opts:
      s3fs-encrypt: "true"
      s3fs-opts: "allow_other,nonempty"
```

### 4. Run the Docker Container
Build and run your Docker container using `docker-compose`.

```sh
docker-compose up -d
```

This setup creates an encrypted Docker volume using the `rexray` plugin, mounts it in your container, and ensures that the data at rest is encrypted. The volume is configured to be read-only within the container to enhance security further.

### Additional Considerations
- **Ensure Docker Plugin Compatibility**: Ensure that the Docker plugin you choose supports encryption and is compatible with your Docker setup.
- **Volume Encryption Options**: Different plugins may have different options for enabling and configuring encryption. Refer to the plugin’s documentation for specific details.
- **Access Control**: Limit access to the container and the encrypted volume to only those who need it. Use Docker's user and group management features to control access.

By following these steps, you can create and use an encrypted volume in Docker, ensuring that your data at rest is securely encrypted.
